nelmio_cors:
    defaults:
        allow_credentials: false
        origin_regex: false
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: []
        max_age: 3600
    paths:
        '^/dashboard/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['PATCH', POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['PATCH', POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['^localhost$']
