api_platform:
    resource: .
    type: api_platform
    prefix: /dashboard
#    swagger:
#        api_keys:
#            JWT:
#                name: Authorization
#                type: header
api_authentication:
    path: /dashboard/login_check
