<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNnCrSxB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNnCrSxB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNnCrSxB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNnCrSxB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNnCrSxB\App_KernelDevDebugContainer([
    'container.build_hash' => 'NnCrSxB',
    'container.build_id' => '8328442d',
    'container.build_time' => 1631816839,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNnCrSxB');
