<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4D7qsUn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4D7qsUn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4D7qsUn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4D7qsUn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4D7qsUn\App_KernelDevDebugContainer([
    'container.build_hash' => '4D7qsUn',
    'container.build_id' => 'afef67ff',
    'container.build_time' => 1631730323,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4D7qsUn');
