<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKgStxZl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKgStxZl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKgStxZl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKgStxZl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKgStxZl\App_KernelDevDebugContainer([
    'container.build_hash' => 'KgStxZl',
    'container.build_id' => '0ed2e586',
    'container.build_time' => 1631885629,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKgStxZl');
